tabs:
  main:
    display: Main
    sections:
      -
        display: Scheduled Events
        fields:
          -
            handle: do_you_run_events
            field:
              type: yes_no
              display: 'Do you run events?'
          -
            handle: do_you_run_online_events
            field:
              type: yes_no
              display: 'Do you run online events?'
          -
            handle: do_you_run_face_to_face_events
            field:
              type: yes_no
              display: 'Do you run face-to-face events?'
          -
            handle: do_you_run_face_to_face_events_at_your_members_offices
            field:
              type: yes_no
              display: "Do you run face-to-face events at your member's offices?"
          -
            handle: for_these_events_do_you_not_know_who_the_attendees_will_be_until_you_arrive_there
            field:
              type: yes_no
              display: 'For these events do you not know who the Attendees will be until you arrive there?'
          -
            handle: for_your_online_events_do_you_use_teams
            field:
              type: yes_no
              display: 'For your online events do you use Teams?'
          -
            handle: for_your_online_events_do_you_use_zoom
            field:
              type: yes_no
              display: 'For your online events do you use Zoom?'
          -
            handle: do_you_run_some_or_all_of_your_online_events_where_the_delivery_platform_is_an_lms
            field:
              type: yes_no
              display: 'Do you run some or all of your online events where the delivery platform is an LMS?'
          -
            handle: do_you_already_have_an_lms_that_you_wish_to_retain
            field:
              type: yes_no
              display: 'Do you already have an LMS that you wish to retain?'
          -
            handle: for_your_face_to_face_events_do_you_wish_to_capture_a_registrants_dietary_requirements
            field:
              type: yes_no
              display: "For your face-to-face events do you wish to capture a Registrant's dietary requirements?"
          -
            handle: do_you_require_support_for_dietary_requirements_as_a_free_text_field_where_anything_can_be_entered_or_a_list_of_options_or_a_list_of_options_with_a_free_text_field_at_the_bottom_typically_called_other
            field:
              type: yes_no
              display: 'Do you require support for Dietary requirements as a free text field where anything can be entered, or a list of options, or a list of options with a free text field at the bottom (Typically called Other)?'
          -
            handle: do_you_run_member_only_events_whereby_non_members_are_unable_to_register_for_them
            field:
              type: yes_no
              display: 'Do you run member-only events whereby non-members are unable to register for them?'
          -
            handle: for_your_member_only_events_are_some_or_all_run_by_your_members
            field:
              type: yes_no
              display: 'For your member-only events, are some or all run by your members?'
              instructions: 'i.e.: do not have a licence for the AMS'
          -
            handle: do_you_run_events_that_have_just_member_and_non_member_pricing
            field:
              type: yes_no
              display: 'Do you run events that have just member and non-member pricing?'
          -
            handle: do_you_run_events_that_have_pricing_specific_to_different_memberships
            field:
              type: yes_no
              display: 'Do you run events that have pricing specific to different memberships?'
              instructions: 'E.g.: Student, Full, Retired, Life'
          -
            handle: do_you_require_support_for_early_bird_pricing_across_multiple_date_ranges
            field:
              type: yes_no
              display: 'Do you require support for early-bird pricing across multiple date ranges?'
          -
            handle: could_your_events_attract_attendees_from_different_timezones_and_should_therefore_publish_the_timezone
            field:
              type: yes_no
              display: 'Could your events attract Attendees from different timezones and should therefore publish the timezone?'
          -
            handle: do_you_require_the_ability_to_set_a_registration_close_date_that_is_before_the_event_start_date
            field:
              type: yes_no
              display: 'Do you require the ability to set a registration close date that is before the event start date?'
          -
            handle: do_you_require_the_ability_for_a_registrant_to_go_onto_a_waiting_list_if_the_event_is_full
            field:
              type: yes_no
              display: 'Do you require the ability for a Registrant to go onto a waiting list if the event is full?'
          -
            handle: do_you_require_payment_by_credit_debit_card_payment_for_all_registrations
            field:
              type: yes_no
              display: 'Do you require payment by Credit / Debit card payment for all registrations?'
          -
            handle: do_you_allow_payment_by_invoice_if_the_booker_is_linked_to_an_organisation_that_you_trust
            field:
              type: yes_no
              display: 'Do you allow payment by Invoice if the Booker is linked to an Organisation that you trust?'
          -
            handle: for_payments_do_you_or_do_you_want_to_pass_credit_debit_charge_fees_onto_the_booker
            field:
              type: yes_no
              display: 'For payments, do you, or do you want to, pass Credit / Debit charge fees onto the Booker?'
          -
            handle: do_you_require_paid_registrants_to_be_able_to_access_pre_event_content_online
            field:
              type: yes_no
              display: 'Do you require paid Registrants to be able to access pre-event content online?'
          -
            handle: do_you_require_paid_registrants_to_be_able_to_access_post_event_content_online
            field:
              type: yes_no
              display: 'Do you require paid Registrants to be able to access post-event content online?'
          -
            handle: for_marking_a_registrant_as_an_attendees_do_you_require_attendee_details_including_dietary_and_special_access_requirements_listed_on_paper
            field:
              type: yes_no
              display: 'For marking a Registrant as an Attendees do you require Attendee details, including dietary and special access requirements, listed on paper?'
          -
            handle: for_marking_a_registrant_as_an_attendees_do_you_require_electronic_support
            field:
              type: yes_no
              display: 'For marking a Registrant as an Attendees do you require electronic support?'
          -
            handle: for_marking_a_registrant_as_an_attendees_do_you_require_electronic_support_by_individuals_who_do_not_have_a_licence_for_the_ams
            field:
              type: yes_no
              display: 'For marking a Registrant as an Attendees do you require electronic support by Individuals who do not have a licence for the AMS?'
          -
            handle: do_you_require_discount_codes_that_are_percentage_based
            field:
              type: yes_no
              display: 'Do you require discount codes that are percentage based?'
              instructions: 'E.g.: 50%, 75%, …'
          -
            handle: do_you_require_discount_codes_that_are_fixed_amount_based
            field:
              type: yes_no
              display: 'Do you require discount codes that are fixed amount based?'
              instructions: 'E.g.: $50, $75, …'
          -
            handle: do_you_require_discount_codes_that_can_only_be_used_once
            field:
              type: yes_no
              display: 'Do you require discount codes that can only be used once?'
          -
            handle: do_you_require_discount_codes_that_can_be_used_multiple_times_up_to_limit
            field:
              type: yes_no
              display: 'Do you require discount codes that can be used multiple times up to limit?'
          -
            handle: do_you_require_the_ability_to_print_event_attendee_badges_with_a_choice_of_fields_like_first_name_preferred_first_name_surname_their_membership_state_company_name_logo_your_logo
            field:
              type: yes_no
              display: 'Do you require the ability to print event Attendee badges with a choice of fields like First Name, Preferred First Name, Surname, their Membership, State, Company Name, Logo, your Logo?'
          -
            handle: do_you_run_post_event_surveys
            field:
              type: yes_no
              display: 'Do you run post event Surveys?'
          -
            handle: do_you_require_the_ability_to_clone_copy_an_event_such_that_all_of_its_configuration_but_not_any_registration_of_course_are_copied_across
            field:
              type: yes_no
              display: 'Do you require the ability to clone (copy) an event such that all of its configuration (but not any registration of course) are copied across?'
          -
            handle: does_the_different_individual_need_to_be_at_the_same_organisation_or_a_child_organisation_as_the_booker
            field:
              type: yes_no
              display: 'Does the different Individual need to be at the same organisation, or a child Organisation, as the Booker?'
          -
            handle: do_you_require_support_for_group_bookings
            field:
              type: yes_no
              display: 'Do you require support for Group Bookings?'
          -
            handle: do_you_require_support_for_group_bookings_whereby_a_booker_can_register_multiple_individuals_and_be_charged_the_price_of_the_registration_according_to_the_registrants_membership_type
            field:
              type: yes_no
              display: 'Do you require support for Group Bookings, whereby a Booker can register multiple Individuals and be charged the price of the registration according to the registrant’s membership type?'
          -
            handle: are_the_group_booking_registrants_only_allowed_to_be_invidividuals_assigned_to_the_organisation_of_the_booker
            field:
              type: yes_no
              display: 'Are the Group Booking Registrants only allowed to be Invidividuals assigned to the Organisation of the Booker?'
          -
            handle: do_you_require_support_for_table_bookings
            field:
              type: yes_no
              display: 'Do you require support for Table Bookings?'
          -
            handle: do_you_sell_table_bookings_at_member_and_non_member_prices
            field:
              type: yes_no
              display: 'Do you sell Table Bookings at member and non-member prices?'
          -
            handle: do_you_require_support_for_your_table_booker_to_be_able_to_assign_and_deassign_attendees_to_their_table_or_tables
            field:
              type: yes_no
              display: 'Do you require support for your table Booker to be able to assign and deassign Attendees to their table (or tables)?'
          -
            handle: are_the_table_registrants_only_allowed_to_be_invidividuals_assigned_to_the_organisation_of_the_booker
            field:
              type: yes_no
              display: 'Are the table Registrants only allowed to be Invidividuals assigned to the Organisation of the Booker?'
      -
        display: 'Personal Details'
        fields:
          -
            handle: first_name
            field:
              type: text
              display: 'First Name'
              width: 50
              validate:
                - required
          -
            handle: last_name
            field:
              type: text
              display: 'Last Name'
              width: 50
          -
            handle: birth_date
            field:
              type: date
              display: 'Birth Date'
          -
            handle: this_is_a_question
            field:
              options:
                'yes': 'Yes'
                'no': 'No'
              type: radio
              display: 'This is a question?'
          -
            handle: this_is_a_question2
            field:
              options:
                'yes': 'Yes'
                'no': 'No'
              type: button_group
              display: 'This is a question 2'
          -
            handle: communication_preference
            field:
              options:
                phone: Phone
                email: Email
              default: email
              type: button_group
              display: 'Communication Preference'
          -
            handle: phone
            field:
              input_type: tel
              type: text
              display: Phone
              if:
                communication_preference: 'equals phone'
              validate:
                - 'required_if:communication_preference,phone'
          -
            handle: email
            field:
              input_type: email
              type: text
              display: Email
              if:
                communication_preference: 'equals email'
              validate:
                - 'required_if:communication_preference,email'
          -
            handle: address
            field:
              type: section
              display: Address
          -
            handle: street_address
            field:
              type: text
              display: 'Street Address'
          -
            handle: street_address_line_2
            field:
              type: text
              display: 'Street Address Line 2'
          -
            handle: city
            field:
              type: text
              display: City
              width: 33
          -
            handle: province
            field:
              type: text
              display: Province
              width: 33
          -
            handle: postal_code
            field:
              input_type: number
              type: text
              display: 'Postal Code'
              width: 33
          -
            handle: yes_no_field
            field:
              type: yes_no
              display: 'Yes No Field'
      -
        display: 'Application Details'
        fields:
          -
            handle: referral
            field:
              options:
                google: Google
                walkin: Walk-In
                social: 'Social Media'
                newspapper: 'Newspapper Ad'
                other: 'Other ( Please Specify )'
              type: checkboxes
              display: 'How were you referred to us ?'
              validate:
                - required
          -
            handle: referral_other
            field:
              type: text
              display: Other
              if:
                referral: 'contains other'
              validate:
                - 'required_if:referral,other'
          -
            handle: resume
            field:
              max_files: 1
              container: assets
              type: assets
              display: Resume
          -
            handle: motivation_letter
            field:
              type: textarea
              display: 'Motivation Letter'
              validate:
                - required
          -
            handle: training_and_certifications
            field:
              type: list
              display: 'Training and Certifications'
              instructions: 'Please use the following format: Training Name - Date'
          -
            handle: references
            field:
              type: list
              display: References
              instructions: 'Please use the following format: Reference Name - Contact or Email'
