tabs:
  main:
    display: Main
    sections:
      -
        display: 'Personal Details'
        fields:
          -
            handle: first_name
            field:
              type: text
              display: 'First Name'
              width: 50
              validate:
                - required
          -
            handle: last_name
            field:
              type: text
              display: 'Last Name'
              width: 50
          -
            handle: birth_date
            field:
              type: date
              display: 'Birth Date'
          -
            handle: communication_preference
            field:
              options:
                phone: Phone
                email: Email
              default: email
              type: button_group
              display: 'Communication Preference'
          -
            handle: phone
            field:
              input_type: tel
              type: text
              display: Phone
              if:
                communication_preference: 'equals phone'
              validate:
                - 'required_if:communication_preference,phone'
          -
            handle: email
            field:
              input_type: email
              type: text
              display: Email
              if:
                communication_preference: 'equals email'
              validate:
                - 'required_if:communication_preference,email'
          -
            handle: mailing_address
            field:
              type: group
              display: 'Mailing Address'
              fields:
                -
                  handle: street_address
                  field:
                    type: text
                    display: 'Street Address'
                    validate:
                      - required
                -
                  handle: street_address_line_2
                  field:
                    type: text
                    display: 'Street Address Line 2'
                -
                  handle: city
                  field:
                    type: text
                    display: City
                    width: 33
                    validate:
                      - required
                -
                  handle: province
                  field:
                    type: text
                    display: Province
                    width: 33
                    validate:
                      - required
                -
                  handle: postal_code
                  field:
                    input_type: number
                    type: text
                    display: 'Postal Code'
                    width: 33
                    validate:
                      - required
      -
        display: 'Application Details'
        fields:
          -
            handle: referral
            field:
              options:
                google: Google
                walkin: Walk-In
                social: 'Social Media'
                newspapper: 'Newspapper Ad'
                other: 'Other ( Please Specify )'
              type: checkboxes
              display: 'How were you referred to us ?'
              validate:
                - required
          -
            handle: referral_other
            field:
              type: text
              display: Other
              if:
                referral: 'contains other'
              validate:
                - 'required_if:referral,other'
          -
            handle: resume
            field:
              max_files: 1
              container: assets
              type: assets
              display: Resume
          -
            handle: motivation_letter
            field:
              type: textarea
              display: 'Motivation Letter'
              validate:
                - required
          -
            handle: training_and_certifications
            field:
              type: list
              display: 'Training and Certifications'
              instructions: 'Please use the following format: Training Name - Date'
          -
            handle: references
            field:
              type: list
              display: References
              instructions: 'Please use the following format: Reference Name - Contact or Email'
